[package]
name = "udp-obfuscat"
version = "1.0.0"
description = "UDP proxy with obfuscation"
license = "ISC"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
clap  = { version = "4.5.0", features = ["derive", "env"] }
env_logger = "0.11.1"
log = "0.4.20"
scopeguard = "1.2.0"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net", "time", "sync"] }
