[package]
name = "udp-obfuscat"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "net", "time"] }
clap  = { version = "4.5.0", features = ["derive"] }
log = "0.4.20"
env_logger = "0.11.1"
base64 = "0.21.7"
anyhow = "1.0.79"
scopeguard = "1.2.0"
