name: Check compilation errors

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Show rust version
        run: rustc --version

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release
